### ISSUE TITLE
user issue: there is error loading the tribehired development

### ISSUE THREAD

**Issue by danielystan** [devansingaram/tribehired#108]
there is error loading the tribehired development
![Untitled-1](https://f.cloud.github.com/assets/3622669/231612/9f2ad642-870c-11e2-8f8f-b1f2e78b05c4.jpg)

**Comment by danielystan** [comment]
this is written by a user to me

**Comment by drewbdennis** [comment]
This is not our problem... That is facebook problem...

**Comment by devansingaram** [comment]
this is what i gather has happened looking at history reports.

At 5.12pm on 7th March, one of our staff logged into tribehiredmail as tribehired connector (facebook id) and invited all his (tribehired connector) friends to our development server.

As the action has been done, we can only make sure it doesn't happen again.

For now, I've disabled the apps from tribehired connector and also changed the password.

@danielystan also do message me your friend's name to make sure that the person is also tribehired.connector's friend.
