### ISSUE TITLE
member applied yesterday without adding number. technically, this field is compulsory

### ISSUE THREAD

**Issue by devansingaram** [devansingaram/tribehired#135]
for position: ceo at 1337 Tech Sdn. Bhd
date: 13 march 2013

**Comment by ykgoon** [comment]
@devansingaram I'm unable to replicate this in staging.

I tried emptying my phone number and then applied for job, I got prompted with a request for contact details.

**Comment by ykgoon** [comment]
Managed to replicate this with the help of Drew.

**Comment by devansingaram** [comment]
Hi @ykgoon,

you mentioned this is done, can we close it?
