### ISSUE TITLE
Job description looks bad when lumped together. People don't read

### ISSUE THREAD

**Issue by devansingaram** [devansingaram/tribehired#139]
Present it properly

**Comment by ykgoon** [comment]
This content is subjected to user input. We need a design solution as opposed to a bug fix, I think this belongs under Enhancement.

My opinion is to reduce the width of paragraph by 50%, assuming we have unlimited height for content display.

**Comment by drewbdennis** [comment]
<p style='margin-top:5px !important;margin-bottom:0 !important;'><strong>People who pinned company </strong></p>

**Comment by drewbdennis** [comment]
fixed and migrated to tribehired
