### ISSUE TITLE
Cannot see jobs people have pinned when going to their profile

### ISSUE THREAD

**Issue by armanatz** [devansingaram/tribehired#179]
When a user goes to someone else's Follow profile, they don't see that person's pinned jobs. This is because the user's skills don't match the jobs the person has pinned on their profile.

Solution:
Have the system show the jobs that match the user's skills first and then show the rest of the jobs after that so the user is not met with nothing

**Comment by ykgoon** [comment]
@armanatz is this fixed by now? I checked http://tribehired.com/follow/armanatz as anonymous and logged in, and I see everything you pinned.
