### ISSUE TITLE
Guest can see who has applied for a job.

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#188]
As a guest i am able to see who has applied for a job. as you can see in the picture i can see Nicholus and Arman have applied for a job.

![image](https://f.cloud.github.com/assets/2082445/333116/16197318-9c47-11e2-8aff-1bc37aa26378.png)

**Comment by devansingaram** [comment]
As a guest, the top section would show login.

You are currently logged in as illumkhan, arman + nicholas are following you. They applied for above jobs, and that's why you see that they applied.
