### ISSUE TITLE
BIG: Email to slow

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#195]
I created a job, pinned, applied for the job and deleted a job. 

I didnt get any email during this span of time. 

There should be a quick email sent out for any of the big action.

**Comment by devansingaram** [comment]
Who didn't get the email, the hirer?

We batch send emails to hirer based on people who apply.

**Comment by illumkhan** [comment]
The hirer didn't get the email. I think I know why.
I was testing on tribehiredmail. the email server is not integrated there right ?
