### ISSUE TITLE
Cant Unapply 

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#196]
Drew to work on it :).

**Comment by ykgoon** [comment]
@illumkhan is this a duplicate of https://github.com/devansingaram/tribehired/issues/180 ?

If so, it's been fixed.

**Comment by illumkhan** [comment]
The apply button goes huge and cant click on it as well.

![image](https://f.cloud.github.com/assets/2082445/350531/b6efe816-a021-11e2-85bc-6d095dbe3fae.png)
