### ISSUE TITLE
Can't add Additional Details to job.

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#197]
Cant add additional details to the job if the text has ' in it.

So need to change the code to help accept text with ' in it. 

Should also be done to all text boxes in the system

**Comment by otkrsk** [comment]
@illumkhan, I've done this. Can you test if this is working on TribeHired? If it works can you help close this issue.

**Comment by illumkhan** [comment]
Tested with this text it works. 

testing position CultureRun is hiring someone PART-TIME to handle our social media channels.
~!@#$%^&*()_+=-`;'":/.,<>?
 You must:
-       have a positive outlook 
-       Have an interest in life-long learning
-       Friendly 
-       Have great if not amazing English writing skills. Other language skills is a plus!
-       Commit 15 hours a week
-       Flexible with time
-       Have a good sense of humour
-       Have a computer with a working internet connection

Daily tasks include:
-     Updating CultureRun's social media channels
-     Content writing
-     Minor admin work

Pay? RM 500/month and you can work from home!
