### ISSUE TITLE
Post a Job Error (6.16pm)

### ISSUE THREAD

**Issue by danielystan** [devansingaram/tribehired#204]
Please take a look and let me know when can be it rectified
![Uploading Post a job error.jpg . . .]()
. Tq!

**Comment by danielystan** [comment]
![Post a job error](https://f.cloud.github.com/assets/3622669/351024/9218f10c-a037-11e2-9139-8ab2960cf3fc.jpg)

**Comment by ykgoon** [comment]
Fixed.
