### ISSUE TITLE
User list has a problem, should not be all the same.

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#231]
All the user are the same name in this job. It should be 40 different people.
http://tribehired.com/dashboard_company/13435460334085/13666113209296?action=candidate&candidateId=13667742396986&isMember=0&hirerId=13187746243184

![image](https://f.cloud.github.com/assets/2082445/418351/da265212-aca0-11e2-8214-669dfabfa15d.png)

**Comment by otkrsk** [comment]
@illumkhan is this bug still happening. I just checked and all users are different.
