### ISSUE TITLE
After viewing a person's job board, going back to home causes only the job(s) that user has pinned to show up and not the landing page (check comments).

### ISSUE THREAD

**Issue by armanatz** [devansingaram/tribehired#233]
To replicate issue:

1) As a guest user, click on someone's name under a job tile and go to their job board.
2) Note job(s) that they have pinned.
3) Click on TribeHired logo on top navbar to go back home.
4) Once in home, user is only shown the previous job(s) they saw on the job board and not all jobs.

**Comment by otkrsk** [comment]
Bug can't be replicated. Closing this issue.
