### ISSUE TITLE
Caching bug: When I access the website, it shows city as mountain view and no jobs

### ISSUE THREAD

**Issue by devansingaram** [devansingaram/tribehired#234]
![27042013_1](https://f.cloud.github.com/assets/1938773/434201/0fcca844-af26-11e2-92ae-9b4f8f6defa2.jpg)

**Comment by ykgoon** [comment]
@devansingaram I searched for "Mountain View" on Live with cache turned off, there is no result shown.

Also, caching does not apply to search results as far as I know. What's your take on this?
