### ISSUE TITLE
Searching for marketing manager does not show the right job.

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#238]
When you search for marketing manager it should show IPO marketing manager job but shows only the first job. What I saw is that the latest job got the most amount of applicants. but the rest of the jobs did not many applicants.
Fixing this bug should increase our applies.
![image](https://f.cloud.github.com/assets/2082445/448341/76b681b6-b240-11e2-82a7-801a04a7f6f9.png)

**Comment by otkrsk** [comment]
Fixed. @illumkhan please check.
