### ISSUE TITLE
Job Description showing /n /r

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#241]
Currently the job description is showing \n\r, this was introduced when we fixed the special characters 

"
1. Develop and market the company\'s wide range of products and services;\r\n\r\n2. Plan and develop programs and business development activities for MAD Incubator\r\n "

There should be such special characters.

**Comment by otkrsk** [comment]
@illumkhan please verify if it is working. I'm going to close this issue for now.

**Comment by otkrsk** [comment]
Reopened, because apparently not fixed yet.

**Comment by otkrsk** [comment]
Should be fixed now.
