### ISSUE TITLE
identical job posting can't be deleted

### ISSUE THREAD

**Issue by danielystan** [devansingaram/tribehired#243]
Identical job posting like Alphapod (1 job post, 1 more clone) and Ezypzy (1 job post, 2 more clones) can't be deleted but if i click 'x', it will bring both the original and clone job post respectively to the pending list. I asked Nicholas and he mentioned (if i got it right) there is needs to be some coding done for it to close one without affecting the other.

**Comment by otkrsk** [comment]
I don't think that the jobs mentioned are identical jobs. EzyPzy has 2 company entries. (EzyPzy Sdn Bhd and EzyPzy Sdn. Bhd.).
