### ISSUE TITLE
Upload Resume: My Name field is not update

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#262]
![image](https://f.cloud.github.com/assets/2082445/660711/7eed6e22-d710-11e2-94b2-b443a980dd34.png)
So I added 123 to my name, my email and my phone number. 
everything seems to be updated here except for My Name.

But the information was not updated on delivery system for My Name, Email and phone number. Nationality was updated.

![image](https://f.cloud.github.com/assets/2082445/660713/e0afc5f6-d710-11e2-8bbf-848f90511980.png)

**Comment by drewbdennis** [comment]
Is the cache on or off...
