### ISSUE TITLE
friend invite + 'my skills'

### ISSUE THREAD

**Issue by danielystan** [devansingaram/tribehired#33]
1) cannot proceed to the the next step after inviting friends (it wipes-out the previous interest chosen when you click 'skip to landing page'). However, it does show when you open a new tab) 

2) problem with editing 'my skills' (see image for this problem)
![error in loading my skills](https://f.cloud.github.com/assets/3622669/166049/887c265c-7984-11e2-9641-379af4b59d65.jpg)

**Comment by drewbdennis** [comment]
Fixed...
