### ISSUE TITLE
Job position  for company ABC sdn bhd (Candidate interested? | Hirer interested? | Hirer interviewed candidate?)

### ISSUE THREAD

**Issue by danielystan** [devansingaram/tribehired#34]
is there a option built for selecting 'yes' or 'no' on the questions as per the title above? 

The current issue is that after clicking on 'Candidate interested', it goes to show 'updated' but I cannot select Yes or No in the next step.

**Comment by otkrsk** [comment]
Currently when you click "Candidate interested" it doesn't update to Yes or No, it just updates the database. In the "Jobs Interested" column, it would display the company that the candidate is interested in applying for.

I will go ahead and close this issue.
