### ISSUE TITLE
Add extra option then just interviewed

### ISSUE THREAD

**Issue by illumkhan** [devansingaram/tribehired#37]
During the interview process, there a few scenarios that could happen and we need to track. 

1) Called the number, number is not working
2) Number is not from singapore/ malaysia
3) Called number, user asked to call back.
4) Called candidate, candidate is not interested / or just go a job

We need to have these options instead of one option saying not interviewed.

**Comment by otkrsk** [comment]
Done. The remarks will be accessible from the Profile button, and you can input the status in the field marked "Remarks".

**Comment by otkrsk** [comment]
Migration hasn't been done, by the way.
