### ISSUE TITLE
individual jobs loaded right for a second and then, it produced a fail whale.

### ISSUE THREAD

**Issue by danielystan** [devansingaram/tribehired#40]
individual jobs loaded right for a second and then, it produced a fail whale.

My steps:
I pasted this URL: tribehired.com/my_landing/jobid?jobId=13584086561000

and got it for a few seconds and then, it showed: http://tribehired.com/whale

**Comment by devansingaram** [comment]
can't recreate error, should be okay now. please try

**Comment by danielystan** [comment]
it's working fine again.
