### ISSUE TITLE
No way for hirer to delete or close job

### ISSUE THREAD

**Issue by devansingaram** [devansingaram/tribehired#58]

**Comment by ykgoon** [comment]
'Close' button added. Hirer has to click Edit first, then find the Close button at the bottom.

Job will be closed with one-click, user will be brought back to the front page.

**Comment by devansingaram** [comment]
Hi @ykgoon,

Just checked our live system and the close the job link is not there

Cheers,
Devan

**Comment by ykgoon** [comment]
@devansingaram I've re-migrated, can you verify that?

**Comment by devansingaram** [comment]
Currently shows: $closeJobLink 

I think on the PHP side need to replace the variable

**Comment by ykgoon** [comment]
OK found it. I need to manage this migration process better. Can you verify?

I can't test on live since I didn't post job there.

**Comment by devansingaram** [comment]
ok it's there now.

@illumkhan you can close the SEGI job now using this method of editing and then close
