### ISSUE TITLE
Detailed feedback from hirer & talent view-points (Need help with answers)

### ISSUE THREAD

**Issue by danielystan** [devansingaram/tribehired#73]
Hi Daniel,

I've tested TribeHired.com and here's my user experience feedback:

From job hunter side:
I've selected only 3 areas that are interesting to me and there is no job postings. Usually if first experience of a user is that there is nothing on the page - they will not come back, ever again. maybe you could still display all ads and only then user can filter out by interest.

From company side:
1. Cool too to integrate job postings on fan page. The huge downside is that it pulls all jobs available, so at my company fan page I end up promoting other company jobs - not cool.
2. There is no option to remove it from fan page. Please advise how do I do it?
3. There is no option to edit job posting.
4. There is no option to delete job posting. I've posted twice as there was an issue with loading first porting, so now I have two postings for same job.
5. How do I receive applications - there is no info on that

Hope this feedback will help you to innovate, and meanwhile please help to remove postings from our fan page. Or can it be only our company posting - this would be ideal.

**Comment by devansingaram** [comment]
Yes, great this is the kind of feedback we need.

Although we are aware of many of this, it helps us to prioritize it

@illumkhan can you (or get someone) convert some or all of this to feature requests if not already. Also i think you can prioritise it.

**Comment by danielystan** [comment]
yes, appreciate it very much on answers I can write back to the hirer/talent. :)

**Comment by devansingaram** [comment]
my suggestion for now is that you have escalated it to our tech team, and you can confirm the team is working on it now, and will get back to hirer as soon as issues are resolved.

On another note, @ykgoon @illumkhan do suggest if we can get a single-point-of-contact support system up?

With such a support system, daniel does not need to be involved at this stage, and support takes over.

**Comment by ykgoon** [comment]
@devansingaram can you elaborate on "support system"? What problem do you intend to solve and for who?

**Comment by devansingaram** [comment]
Good question. 

Our system is not as matured as we would like it to be. Which means the UI/bugs will let hirers down sometimes. 

The problem is that hirers will then always have a perception that our website is slow, or something doesn't work, and not return to the site. Worse, tell that to others.

The goal of the support system is to give hirers peace of mind.

**Comment by ykgoon** [comment]
A full-on customer support tool like GetSatisfaction or Zendesk would definitely do it, but that might be an overkill if we don't have enough dedicated support staff to tackle it.

One other way is to make use of Twitter or FB to capture feedback and then have tech people answer them right there. This can be done via existing TribeHired account or opening new page/account just for support.
